version: '3.7'
services:
  irc-libera-crypt-bot:
    container_name: irc-libera-crypt-bot
    image: ascensive/irc-rss-feed-bot:latest
    restart: always
    logging:
      options:
        max-size: 2m
        max-file: "5"
    volumes:
      - ./libera/feed-bot:/config
    environment:
      TZ: America/New_York
    env_file:
      - ./libera/secrets.env
      - ./libera/feed-bot/tokens.env
  irc-libera-news-bot:
    container_name: irc-libera-news-bot
    image: ascensive/irc-rss-feed-bot:latest
    restart: always
    logging:
      options:
        max-size: 2m
        max-file: "5"
    volumes:
      - ./libera/news-bot:/config
    environment:
      IRCRSSFEEDBOT_ENV: dev
      TZ: America/New_York
    env_file:
      - ./libera/secrets.env
      - ./libera/news-bot/tokens.env
  irc-libera-price-bot:
    container_name: irc-libera-price-bot
    image: ascensive/irc-stock-price-bot:latest
    restart: always
    logging:
      options:
        max-size: 2m
        max-file: "5"
    volumes:
      - ./libera/price-bot:/config
    environment:
      TZ: America/New_York
    env_file:
      - ./libera/secrets.env
  irc-libera-title-bot:
    container_name: irc-libera-title-bot
    image: ascensive/irc-url-title-bot:latest
    restart: always
    logging:
      options:
        max-size: 2m
        max-file: "5"
    volumes:
      - ./libera/title-bot:/config:ro
    env_file:
      - ./libera/secrets.env
    environment:
      TZ: America/New_York
