host: irc.libera.chat
ssl_port: 6697
nick: CryptBot
alerts_channel: '##feeds-alerts'
admin: A1R!reset@user/a1r
mode: +igR
# log:
#   irc: true
defaults:
  shorten: false
feeds:
 '#crypto-feed':
     Ambcrypto:
      url: https://ambcrypto.com/feed
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     BitflyerEurope:
      url: https://blog-eu.bitflyer.com/rss/ https://dailyhodl.com/feed
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     Bitcoin News:
      url:  https://news.bitcoin.com/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     Beincrypto:
      url: https://beincrypto.com/feed
      period: 0.2
      style:
         name:
          bg: orange
          fg: white
     Cointelegraph:
      url: https://cointelegraph.com/rss
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     Cryptoninjas:
      url: https://www.cryptoninjas.net/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     Coinbase:
      url: https://blog.coinbase.com/feed
      period: 0.2
      style:
         name:
          bg: blue
          fg: white    
     Cryptodaily:
      url: https://cryptodaily.co.uk/feed
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
     Cryptomining:
      url: http://cryptomining-blog.com/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     Cryptoslate:
      url: https://cryptoslate.com/feed
      period: 0.2
      style:
        name:
          bg: black
          fg: green
     Decrypt:
      url: https://decrypt.co/feed
      period: 0.2
      style:
         name:
          bg: orange
          fg: white 
     Dailyhodl:
      url: https://dailyhodl.com/feed
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     eToro:
      url: https://www.etoro.com/blog/feed/
      period: 0.2
      style:
         name:
          bg: blue
          fg: white
     FinanceMagnates:
      url: https://www.financemagnates.com/cryptocurrency/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     Newsbtc:
      url: https://www.newsbtc.com/feed
      period: 0.2
      style:
        name:
          bg: orange
          fg: gwhite    
     TheCapital:
      url: https://thecapital.io/assets/feed/news.xml
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     TheMarketsCompass:
      url: https://themarketscompass.substack.com/feed
      period: 0.2
      style:
         name:
          bg: orange
          fg: white   
     TheMoon:
      url: https://medium.com/feed/the-moon
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     TheBullish:
      url: https://medium.com/feed/the-bullish
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     Unchained:
      url: https://unchainedpodcast.com/category/unconfirmed/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     Zycrypto:
      url: https://zycrypto.com/feed
      period: 0.2
      style:
        name:
          bg: black
          fg: green
 '#macanudos':
    futuragora:
      url: https://futuragora.pt/feed
      period: 1
      style:
        name:
          bg: red
          fg: white
    macanudos:
      url: https://macanudos.org/feed
      period: 0.2
      style:
        name:
          bg: white
          fg: orange
 '#monero-pt':
    pt-Cryptofcafe:
      url: https://www.cryptocafe.pt/feed/podcast
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
