host: irc.libera.chat
ssl_port: 6697
nick: CryptBot
alerts_channel: '##feeds-alerts'
admin: A1R!reset@user/a1r
mode: +igR
# log:
#   irc: true
defaults:
  shorten: false
feeds:
 '#crypto-feed':
     BitflyerEurope:
      url: https://blog-eu.bitflyer.com/rss/
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
     Bitcoin News:
      url:  https://news.bitcoin.com/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
      Beincrypto:
      url: https://beincrypto.com/feed
      period: 0.2
      style:
         name:
          bg: orange
          fg: grey
     Cointelegraph:
      url: https://cointelegraph.com/rss
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
     Cryptoninjas:
      url: https://www.cryptoninjas.net/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
     Coindesk:
      url: https://cointelegraph.com/rss
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
      Coinbase:
      url: https://blog.coinbase.com/feed
      period: 0.2
      style:
         name:
          bg: orange
          fg: grey    
     Cryptodaily:
      url: https://cryptodaily.co.uk/feed
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
     Cryptomining:
      url: http://cryptomining-blog.com/feed/
      period: 0.2
      style:
        name:
          bg: grey
          fg: orange
      Decrypt:
      url: https://decrypt.co/feed
      period: 0.2
      style:
         name:
          bg: orange
          fg: grey 
      eToro:
      url: https://www.etoro.com/blog/feed/
      period: 0.2
      style:
         name:
          bg: orange
          fg: grey
     FinanceMagnates:
      url: https://www.financemagnates.com/cryptocurrency/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
      Kraken:
      url: https://beincrypto.com/feed
      period: 0.2
      style:
         name:
          bg: orange
          fg: grey
     Newsbtc:
      url: https://www.newsbtc.com/feed
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
      Paxfull:
      url: https://paxful.com/blog
      period: 0.2
      style:
         name:
          bg: orange
          fg: grey     
     TheCapital:
      url: https://thecapital.io/assets/feed/news.xml
      period: 0.2
      style:
        name:
          bg: orange
          fg: gray
      TheMarketsCompass:
      url: https://themarketscompass.substack.com/feed
      period: 0.2
      style:
         name:
          bg: orange
          fg: grey   
    TheMoon:
      url: https://medium.com/feed/the-moon
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
     TheBullish:
      url: https://medium.com/feed/the-bullish
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
     Unchained:
      url: https://unchainedpodcast.com/category/unconfirmed/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
 '#macanudos':
    futuragora:
      url: https://futuragora.pt/feed
      period: 1
      style:
        name:
          bg: red
          fg: white
    macanudos:
      url: https://macanudos.org/feed
      period: 0.2
      style:
        name:
          bg: white
          fg: orange
  '#monero-pt':
    pt-Cryptofcafe:
      url: https://www.cryptocafe.pt/feed/podcast
      period: 0.2
      style:
        name:
          bg: white
          fg: orange
