host: irc.libera.chat
ssl_port: 6697
nick: CryptBot
alerts_channel: '##feeds-alerts'
admin: A1R!reset@user/a1r
mode: +igR
# log:
#   irc: true
defaults:
  shorten: false
feeds:
"#macanudos":
    macanudos.org:
      url: https://macanudos.org/feed
      period: 0.2
      shorten: false
    futuragora.pt:
      url: https://futuragora.pt/feed
      period: 0.2
      shorten: false
      
  '#crypto-feed':
    Cointelegraph:
      url: https://cointelegraph.com/rss
      period: 1
      style:
        name:
          bg: red
          fg: white
          bold: false
    pt-Cryptofcafe:
      url: https://www.cryptocafe.pt/feed/podcast
      period: 0.2
      style:
        name:
          bg: white
          fg: orange
          bold: false
    Cryptodaily:
      url: https://cryptodaily.co.uk/feed
      period: 0.2
    Cryptomining:
      url: http://cryptomining-blog.com/feed/
      period: 0.2
    FinanceMagnates:
      url: https://www.financemagnates.com/cryptocurrency/feed/
      period: 0.2
    Newsbtc:
      url: https://www.newsbtc.com/feed
      period: 0.2
    TheMoon:
      url: https://medium.com/feed/the-moon
      period: 0.2
    Unchained:
      url: https://unchainedpodcast.com/category/unconfirmed/feed/
      period: 0.2
    pt-Futuragora:
      url: https://futuragora.pt/feed/
      period: 0.2
      
