host: irc.libera.chat
ssl_port: 6697
nick: CryptBot
alerts_channel: '##feeds-alerts'
admin: A1R!reset@user/a1r
mode: +igR
# log:
#   irc: true
defaults:
  shorten: false
feeds:
  '#crypto-feed': &CryptoFeeds
     AmbCrypto:
      url: https://ambcrypto.com/feed
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     BitflyerEu:  # If this feed name is updated, also update it for #us-market-news
      url: https://blog-eu.bitflyer.com/rss/
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     Bitcoin.com:
      url:  https://news.bitcoin.com/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     BeInCrypto:
      url: https://beincrypto.com/feed
      period: 0.2
      style:
         name:
          bg: orange
          fg: white
     Cointelegraph:
      url: https://cointelegraph.com/rss
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     Cryptoninjas:
      url: https://www.cryptoninjas.net/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     BitcoinMag:
      url: https://bitcoinmagazine.com/.rss/full/
      period: 0.2
      style:
         name:
          bg: blue
          fg: white
     CryptoDailyUK:
      url: https://cryptodaily.co.uk/feed
      period: 0.2
      style:
        name:
          bg: orange
          fg: grey
     CryptoMining:
      url: http://cryptomining-blog.com/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     CryptoSlate:
      url: https://cryptoslate.com/feed
      period: 0.2
      style:
        name:
          bg: black
          fg: green
     Decrypt:
      url: https://decrypt.co/feed
      period: 0.2
      style:
         name:
          bg: orange
          fg: white
     DailyHodl:
      url: https://dailyhodl.com/feed
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     eToro:
      url: https://www.etoro.com/blog/feed/
      period: 0.2
      style:
         name:
          bg: blue
          fg: white
     FinanceMagnates:
      url: https://www.financemagnates.com/cryptocurrency/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     NewsBTC:
      url: https://www.newsbtc.com/feed
      period: 0.2
      style:
        name:
          bg: orange
          fg: gwhite
     TheCapital:
      url: https://thecapital.io/assets/feed/news.xml
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     TheMarketsCompass:
      url: https://themarketscompass.substack.com/feed
      period: 0.2
      style:
         name:
          bg: orange
          fg: white
     TheMoon:
      url: https://medium.com/feed/the-moon
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     TheBullish:
      url: https://medium.com/feed/the-bullish
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     Unchained:
      url: https://unchainedpodcast.com/category/unconfirmed/feed/
      period: 0.2
      style:
        name:
          bg: orange
          fg: white
     ZyCrypto:
      url: https://zycrypto.com/feed
      period: 0.2
      style:
        name:
          bg: black
          fg: green
  '#macanudos':
    futuragora:
      url: https://futuragora.pt/feed
      period: 3
      style:
        name:
          bg: red
          fg: white
    macanudos:
      url: https://macanudos.org/feed
      period: 3
      style:
        name:
          bg: white
          fg: orange
  '#monero-pt':
    pt-Cryptofcafe:
      url: https://www.cryptocafe.pt/feed/podcast
      period: 3
      style:
        name:
          bg: orange
          fg: white
  '#us-market-news':
    <<: *CryptoFeeds
    BitflyerEu:
      url: https://blog-eu.bitflyer.com/rss/
      period: 9876543  # This high period effectively disables the feed in the channel.
